version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis-db
    volumes:
      - ./:/app

  redis-db:
    image: redis:alpine